version: "2"
services:
    client:
        image: ohsiha-client
        restart: always
        container_name: ohsiha-client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - api
        build: client/

    api:
        image: ohsiha-api
        restart: always
        container_name: ohsiha-api
        ports:
            - "5000:5000"
        volumes:
            - ./server:/server
            - /server/node_modules
        build: server/
